### PR TITLE
South Africa testing centers (hospitals only,for now)

### LINKED ISSUE #24: Add ZAF hospitals from https://github.com/dsfsi/covid19za

### PR DESCRIPTION
**Pull request by elolelo**
There is outstanding data about the Gift of the Givers's Testing centers' locations and some public clinics - will send those once recieved.

The data sources are the webpages appended in the json file

I decided to use Zulu as the language not only to diversify languages but also because it is a  language said to be spoken by a majority of South African.Translations are available should some need to stick to English

### CODE REVIEW

**Comment by IneffableKoD** [comment]
Fantastic, thank you so much @elolelo! I'll run a quick test and then merge your request.

Sorry, approval was too quick, there is a conflict. Looking into it.

**Review by IneffableKoD — APPROVED** [review]
~~Thank you very much, checked, and approved. ~~

Conflict detected, need to have another look.

**Comment by IneffableKoD** [comment]
Dear @elolelo so sorry for the mess I made in the review. There is a conflict on the testsitesZAF.js file. Somehow 2 records got mixed up I think. Could you have a look, please?

**Comment by elolelo** [comment]
Dear @IneffableKoD , I think is more than 1 change is taking place on this file. For now, I will close this  pull request and create a new one.

**Comment by IneffableKoD** [comment]
Yes there was another PR waiting on the same file that I approved. Sorry again!

**Pull request closed without merging**
